name: dashdeals deployment pipeline

on:
  push:
    branches: 
      - main
  pull_request: 
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy backend to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: backend
          prod: true

frontend:
    runs-on: ubuntu-latest
    needs: backend
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install frontend dependencies
        run: pnpm install

      - name: Lint frontend
        run: pnpm run lint

      - name: Test frontend
        run: pnpm test

      - name: Build frontend
        run: pnpm run build

      - name: Install Firebase CLI
        run: pnpm install -g firebase-tools

      - name: Deploy frontend to Firebase
        run: firebase deploy --only hosting
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}